# -*- coding: utf-8 -*-
import io

lines = [
    '<!-- home/index.wxml -->',
    '<view class="home-container">',
    '  <view class="navbar">',
    '    <view class="navbar-left">',
    '      <text class="navbar-title">\u5ba0\u7269\u65e5\u5e38\u8bb0\u5f55</text>',
    '    </view>',
    '    <view class="navbar-right">',
    '      <view class="navbar-icon" bindtap="switchPet">',
    '        <text class="icon">\U0001f43e</text>',
    '        <text class="pet-name" wx:if="{{currentPet}}">{{currentPet.name}}</text>',
    '        <text class="pet-name" wx:else>\u9009\u62e9\u5ba0\u7269</text>',
    '      </view>',
    '    </view>',
    '  </view>',
    '  <scroll-view class="main-content" scroll-y>',
    '    <view class="date-section">',
    '      <view class="date-header">',
    '        <text class="month">{{currentMonth}}</text>',
    '        <view class="date-nav">',
    "          <text class=\"nav-btn\" bindtap=\"prevDay\">\u2039</text>",
    '          <text class="current-date">{{currentDate}}</text>',
    "          <text class=\"nav-btn\" bindtap=\"nextDay\">\u203a</text>",
    '        </view>',
    '      </view>',
    '      <scroll-view class="horizontal-calendar" scroll-x>',
    '        <view class="calendar-days">',
    "          <view class=\"day-item {{day.isSelected ? 'selected' : ''}} {{day.hasRecord ? 'has-record' : ''}}\" wx:for=\"{{calendarDays}}\" wx:key=\"date\" data-date=\"{{day.date}}\" bindtap=\"selectDate\">",
    '            <text class="day-week">{{day.week}}</text>',
    '            <text class="day-date">{{day.day}}</text>',
    '            <view class="day-indicator" wx:if="{{day.hasRecord}}"></view>',
    '          </view>',
    '        </view>',
    '      </scroll-view>',
    '    </view>',
    '    <view class="records-section">',
    '      <view class="module-section">',
    '        <view class="module-header">',
    '          <text class="module-title">\u65e5\u5e38\u8bb0\u5f55</text>',
    '          <text class="module-subtitle">Daily Routine</text>',
    '        </view>',
    '        <view class="module-divider"></view>',
    '        <view class="cards-grid">',
    '          <view class="card-item" bindtap="recordFeeding"><view class="card-icon">\U0001f37d\ufe0f</view><text class="card-title">\u996e\u98df</text><text class="card-subtitle">{{recordSummaries.feeding}}</text></view>',
    '          <view class="card-item" bindtap="recordHydration"><view class="card-icon">\U0001f4a7</view><text class="card-title">\u996e\u6c34</text><text class="card-subtitle">{{recordSummaries.hydration}}</text></view>',
    '          <view class="card-item" bindtap="recordExcretion"><view class="card-icon">\U0001f6bd</view><text class="card-title">\u6392\u6ccf</text><text class="card-subtitle">{{recordSummaries.excretion}}</text></view>',
    '          <view class="card-item" bindtap="recordActivity"><view class="card-icon">\U0001f3c3</view><text class="card-title">\u8fd0\u52a8</text><text class="card-subtitle">{{recordSummaries.activity}}</text></view>',
    '          <view class="card-item" bindtap="recordSleep"><view class="card-icon">\U0001f634</view><text class="card-title">\u7761\u7720</text><text class="card-subtitle">{{recordSummaries.sleep}}</text></view>',
    '          <view class="card-item" bindtap="recordMood"><view class="card-icon">\U0001f60a</view><text class="card-title">\u60c5\u7eea</text><text class="card-subtitle">{{recordSummaries.mood}}</text></view>',
    '        </view>',
    '      </view>',
    '      <view class="module-section">',
    '        <view class="module-header">',
    '          <text class="module-title">\u5065\u5eb7\u7ba1\u7406</text>',
    '          <text class="module-subtitle">Medical &amp; Care</text>',
    '        </view>',
    '        <view class="module-divider"></view>',
    '        <view class="cards-grid">',
    '          <view class="card-item" bindtap="recordVaccine"><view class="card-icon">\U0001f489</view><text class="card-title">\u75ab\u82d7</text><text class="card-subtitle">\u9884\u9632\u533b\u7597</text></view>',
    '          <view class="card-item" bindtap="recordDeworming"><view class="card-icon">\U0001f41b</view><text class="card-title">\u9a71\u866b</text><text class="card-subtitle">\u9884\u9632\u533b\u7597</text></view>',
    '          <view class="card-item" bindtap="recordGrooming"><view class="card-icon">\U0001f6c1</view><text class="card-title">\u62a4\u7406</text><text class="card-subtitle">\u6e05\u6d01\u7f8e\u5bb9</text></view>',
    '          <view class="card-item" bindtap="recordMedical"><view class="card-icon">\U0001f3e5</view><text class="card-title">\u533b\u7597</text><text class="card-subtitle">\u5c31\u8bca\u7528\u836f</text></view>',
    '        </view>',
    '      </view>',
    '    </view>',
    '    <view class="bottom-space"></view>',
    '  </scroll-view>',
]

with io.open('d:/FurForever/miniprogram/pages/home/index.wxml', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('part1 done')

